version: 2.1
orbs:
  python: circleci/python@2.1.1
  docker: circleci/docker@2.2.0
jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
        requirements-file: requirements.txt
      - run:
          name: Set Secret Key
          command: |
            set SECRET_KEY=%SECRET_KEY%
            echo SECRET_KEY=%SECRET_KEY% >> %BASH_ENV%
      - run:
          name: Collect statics for interface
          command: |
            python manage.py collectstatic --noinput
      - persist_to_workspace:
          root: "~"
          paths:
            - .

  test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - attach_workspace:
          at: "~"
      - run: python -m pytest
      - run: flake8


  build_and_push_image:
    executor: docker/default
    steps:
      - checkout
      - attach_workspace:
          at: "~"
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build and push docker image
          command: |
            docker build -t clementroy/OangeCountyLettings:latest .
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push clementroy/OangeCountyLettings:latest




workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - build_and_push_image:
          requires:
            - build
            - test
