version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: "Set Secret Key"
          command: |
            echo $SECRET_KEY

      - run: pip install -r requirements.txt
      - run: python manage.py collectstatic --noinput

  test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: pip install -r requirements.txt 
      - run: python pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
