version: 2.1
orbs:
  python: circleci/python@2.1.1
  docker: circleci/docker@2.2.0
jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
        requirements-file: requirements.txt
      - run:
          name: Set Secret Key
          command: |
            set SECRET_KEY=%SECRET_KEY%
            echo SECRET_KEY=%SECRET_KEY% >> %BASH_ENV%
      - run:
          name: Collect statics for interface
          command: |
            python manage.py collectstatic --noinput
      - persist_to_workspace:
          root: "~"
          paths:
            - .

  test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - attach_workspace:
          at: "~"
      - run: python -m pytest
      - run: flake8

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
