version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
        requirements-file: requirements.txt
      - run:
          name: Set Secret Key
          command: |
            set SECRET_KEY=%SECRET_KEY%
            echo SECRET_KEY=%SECRET_KEY% >> %BASH_ENV%
      - run:
          name: Collect statics for interface
          command: |
            python manage.py collectstatic --noinput

  test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: pip install -r requirements.txt 
      - run: python -m pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
